-- Execute este arquivo no SQL Editor do seu projeto Supabase.
-- Antes de executar: em Authentication > Providers, habilite Anonymous sign-ins.

create table if not exists public.votos_mais_provavel (
    id bigint generated by default as identity primary key,
    pergunta_id smallint not null check (pergunta_id between 1 and 10),
    participante text not null check (participante in ('Araujo', 'Jô', 'Fenili', 'Maju', 'Edi', 'Tali', 'Piovesan')),
    usuario_id uuid not null default auth.uid(),
    criado_em timestamptz not null default now(),
    constraint um_voto_por_pessoa_em_cada_pergunta unique (pergunta_id, usuario_id)
);

alter table public.votos_mais_provavel enable row level security;

revoke all on table public.votos_mais_provavel from anon;
grant insert on table public.votos_mais_provavel to authenticated;
grant usage on sequence public.votos_mais_provavel_id_seq to authenticated;

create policy "Pessoas autenticadas votam apenas por si"
on public.votos_mais_provavel
for insert
to authenticated
with check (usuario_id = (select auth.uid()));

create or replace function public.resultado_mais_provavel(p_pergunta_id smallint)
returns table (participante text, total bigint)
language sql
stable
security definer
set search_path = public
as $$
    select v.participante, count(*)::bigint as total
    from public.votos_mais_provavel as v
    where v.pergunta_id = p_pergunta_id
    group by v.participante
    order by total desc, v.participante asc;
$$;

revoke all on function public.resultado_mais_provavel(smallint) from public;
grant execute on function public.resultado_mais_provavel(smallint) to authenticated;
